# Question 1

## Section 1.1

In [1]:
import numpy as np

In [2]:
# Load the iris dataset from the fisheriris.data file and place them in an array iris_data numpy.genfromtxt
iris_data = np.loadtxt('fisheriris.data',dtype = float, delimiter=',')

In [3]:
#Load the attributes from the attributes.txt file and place them in a list feature_names
feature_names = list(np.genfromtxt('attributes.txt',dtype = str ,delimiter=','))

In [4]:
#Then load the feature names from the feature.txt file and place them in a vector target_names.
target_names = np.genfromtxt('feature.txt',dtype = str ,delimiter = ',')

In [ ]:
'''
Ans 1.1 :- The genfromtxt function provides more sophisticated handling of, e.g., lines with missing values.

numpy.genfromtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0,
                 converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None,
                 deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i',
                 unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
                 
numpy.loadtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None,
              unpack=False, ndmin=0)
'''

## Section 1.2

In [5]:
# Pull out the column related to the class from the irirs_data array and place it in an integer vector named target.
target = []
for i in range(0,len(iris_data)):
    target.append(iris_data[i][4])
target = np.asarray(target, dtype= int)
print('Target labels are as follows :- \n' + str(target))

Target labels are as follows :- 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
# Then remove the class column from the irirs_data array
iris_data = np.delete(iris_data, [4], axis=1)
print('Iris data after removing the class column :- \n' + str(iris_data))

Iris data after removing the class column :- 
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3

In [8]:
# Remove the ‘Class’ from the feature_names list
feature_names.remove('class')
print('Features list after removing class from it  :- \n' + str(feature_names))

Features list after removing class from it  :- 
['sepal length in cm', 'sepal width in cm', 'petal length in cm', 'petal width in cm']


In [9]:
# Find the size of the Fisher's measurements
size = iris_data.shape
print('Size of the Fishers measurements  :- \n' + str(size))

Size of the Fishers measurements  :- 
(150, 4)


In [10]:
# Show the number of elements of the second dimension of the irirs_data array
numOfElements = iris_data.shape[1]
print('Number of elements of the second dimension of the irirs_data array  :- \n' + str(numOfElements))

Number of elements of the second dimension of the irirs_data array  :- 
4


## Section 1.3

In [ ]:
'''
Find the sums of each of the columns in the irirs_data array. Find the sums of just the second and the fourth columns.
Pull out samples (rows) 27 through 48 and find the maximum values in each of the four columns of this set of samples.
Pull out the odd-numbered samples (rows) between the third and 33rd rows and find the minimum values in the first two
columns. Capture the output to show your work. Hint: you can use numpy.ndarray functions.
'''

In [11]:
# Find the sums of each of the columns in the irirs_data array
sumCol = np.empty((1,4), dtype = float)
for i in range(4):
    sumCol[:,[i]] = np.sum(iris_data[:,i])
print('Sum of each of the columns in the iris_data :-')
print(str(float(sumCol[:,0])) +' '+ str(float(sumCol[:,1])) +' '+ str(float(sumCol[:,2]))+' '+ str(float(sumCol[:,3])) )

Sum of each of the columns in the iris_data :-
876.5 458.1 563.8 179.8


In [12]:
# Find the sums of just the second and the fourth columns
sumCol24 = sumCol[:,1] + sumCol[:,3]
print('Sum of column 2nd and 4th is :- \n' + str(float(sumCol24)))

Sum of column 2nd and 4th is :- 
637.9000000000001


In [ ]:
# (Inner outer Bounds) Pull out samples (rows) 27 through 48 and find the maximum values in each of the four columns of this set of samples.
maxCol = np.empty((1,4), dtype = float)
for i in range(4):
    maxCol[:,[i]] = np.max(iris_data[27:48,i])
print('Max of each of the columns in the iris_data :-')
print(str(float(maxCol[:,0])) +' '+ str(float(maxCol[:,1])) +' '+ str(float(maxCol[:,2]))+' '+ str(float(maxCol[:,3])))

In [ ]:
# Pull out the odd-numbered samples (rows) between the third and 33rd rows and find the minimum values in the first two columns.
minCol1 = np.min(iris_data[3:33:2,0])
minCol2 = np.min(iris_data[3:33:2,1])
print('Between the odd numbered samples between third and 33rd rows the minimum values in the first two columns :-')
print(str(minCol1)+' '+str(minCol2))

## Section 1.4

In [ ]:
'''
Add the first and the third columns and place the results in a vector r13rd, then sum up r13rd.
Compute the value each value of r13rd cubed.
'''

In [ ]:
# Add the first and the third columns and place the results in a vector r13rd
r13rd = iris_data[:,[0,2]].sum(1)
print(r13rd)

In [ ]:
# Sum up r13rd
np.sum(r13rd)

In [ ]:
#Compute the value each value of r13rd cubed.
r13rdCubed = np.power(r13rd,3)
print('Cobbed r13rd matrix is as follows :- \n'+ str(r13rdCubed))

## Section 1.5

In [ ]:
# Extract the first 4 rows of the first two columns as mat1 and first 4 rows of the last two columns as mat2.
mat1 = iris_data[0:4, [0,1]]
mat2 = iris_data[0:4, [2,3]]
print('The two matrices are as follows :-')
print('Mat1 : \n '+str(mat1) +' \n\n'+ 'Mat2 : \n '+str(mat2))

In [ ]:
# Add mat1 to mat2.
sumMat = np.add(mat1, mat2)
print('Sum of the matrices :- \n'+ str(sumMat))

In [ ]:
# Multiple the respective elements of mat1 and mat2.
multMat = np.multiply(mat1, mat2)
print('Multiplication of the matrices :- \n'+ str(multMat))

## Section 1.6

In [ ]:
# Calculate the inner product of mat1 and mat2 and store it in mat3.
mat3 = np.inner(mat1, mat2)
print('Inner product of mat1 and mat2 is :- \n'+ str(mat3))

In [ ]:
# Write mat3 out in CSV format to a file call mat3.CSV (hint: you can use numpy.savetxt function).
np.savetxt('mat3.csv', mat3)
print('Wrote mat3 matrix out in CSV format to a file call mat3.CSV')

## Section 1.7

In [ ]:
'''
Use a bar plot to show the mean and standard deviation of each value of Fisher's measurements.
Hint: use matplotlib.pyplot module. Add proper axis label and title for the plot.
'''

import numpy as np
import matplotlib.pyplot as plt
arrMean = [np.mean(iris_data[:,[i]]) for i in range(4)] 
arrStd =  [np.std(iris_data[:,[i]]) for i in range(4)] 


N = 4

locx = np.arange(N)  # the x locations for the groups
width = 0.15       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(locx, arrMean, width, color='r' )
rects2 = ax.bar(locx + width, arrStd, width, color='y')

ax.set_ylabel('Statistical Values')
ax.set_title('Standard deviation and mean of different features')
ax.set_xticks(locx + width / 2)
ax.set_xticklabels(tuple(feature_names))

ax.legend((rects1[0], rects2[0]), ('Mean', 'Standard Deviation'))

plt.show()

## Section 1.8

In [ ]:
'''
Plot the three species class examples as different colour points in a scatter plot as a function of the first two 
variables in the data array. Add axis labels and legend for the scatter plot using the target_names and feature_names.
Add a proper title for the plot.
'''

In [ ]:
import matplotlib.pyplot as plt
dataScatter = iris_data[:,[0,1]].T
counter = [list(target).count(i) for i in range(np.max(target)+1)]

lb1 = plt.scatter(dataScatter[0][0:counter[0]], dataScatter[1][0:counter[0]], color = 'b', label = 'salil')
lb2 = plt.scatter(dataScatter[0][50:50 + counter[1]], dataScatter[1][50:50 + counter[1]], color = 'g', label = 'vishnu')
lb3 = plt.scatter(dataScatter[0][50+50 : 50+ 50+ counter[2]], dataScatter[1][50+50 : 50+ 50+ counter[2]], color = 'r', label = 'kapur')

plt.xlabel(feature_names[0])
plt.ylabel(feature_names[1])

plt.legend((lb1, lb2, lb3), target_names, scatterpoints=1, loc='upper right', fontsize=8)

plt.title('Classification results')

plt.show()

## Section 1.9

In [ ]:
'''
Using a for loop and matplotlib.pyplot.subplot and itertools modules,
plot 6 scatter plots of all combinations of two features in one plot.
Hint: you should adjust proper blank spaces between subplots.
'''

In [ ]:
import matplotlib.pyplot as plt
import itertools

# for loop to get a multidimensional array with 6 rows
count = 1
features = [0, 1, 2, 3]
for subset in itertools.combinations(features, 2):
        dataScatter = iris_data[:,[subset[0],subset[1]]].T
        plt.subplot(int(str(32) +''+ str(count)))
        plt.scatter(dataScatter[0], dataScatter[1], c = target)       
        plt.xlabel(feature_names[subset[0]])
        plt.ylabel(feature_names[subset[1]])
        plt.subplots_adjust( hspace= 0.5 )
        count+=1
plt.show()

## Section 1.10

In [ ]:
 '''
 Random sampling is a very important core technique in machine learning.
 Look up seed, RandomState, rand, randn, and randint functions in numpy.
 random module to briefly explain about the properties and capabilities of these commands.
 Explain a scenario that you must use RandomState before the random generator function.
 Create a 5 x 5 matrix call cent consisting of random values drawn from the normal distribution.
 Explain why there are negative values in cent. Create another 5 x 5 matrix call cent_fix consisting of random
 values drawn from the normal distribution with fix pseudo random number using RandomState method.
 Try different seeds and check the values of the cent and cent_fix arrays and capture the output to show your work.
 '''   

In [ ]:
#Random sampling is a very important core technique in machine learning.
#Look up seed, RandomState, rand, randn, and randint functions in numpy.
#Random module to briefly explain about the properties and capabilities of these commands.
#Explain a scenario that you must use RandomState before the random generator function.

# rand :- Always gives value between [0,1) by following a uniform distribution and this value is 
#          numpy.random.rand(d0, d1, ..., dn)¶
print('A matrix of Random number :- \n'+ str(np.random.rand(2,5))) 


# seed :- Here we Initialize the random number generator. So with this everytime we generate a set of random numbers
#         they come out to be same.  
np.random.seed(5)
print('\nOn every re run these values remain the same set of values :- ')
print(np.random.rand())
print(np.random.rand())

# randint :- This generates a random number between the lower limit and upper limit both inclusive. 
#            random.randint(a, b)
#            Return a random integer N such that a <= N <= b.
print('\nA random integer between 1 and 10 :- '+ str(np.random.randint(1, 10)))

# randn :-  numpy.random.randn(d0, d1, ..., dn)
#           Return a sample (or samples) from the “standard normal” distribution.
#           If positive, int_like or int-convertible arguments are provided,
#           randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from
#           a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 
#           (if any of the d_i are floats, they are first converted to integers by truncation).
#           A single float randomly sampled from the distribution is returned if no argument is provided.
print('\nA matrix of random numbers which even has negative numbers:- \n'+ str(np.random.randn(2, 4)))     

# RandomState :- Given seed so as to tell the random generator function not to generate some sort of
#                diffrenet values everytime. Using this you give the seed to this and you don't 
#                need to explicitely give the seed.
gen = np.random.RandomState(4)
print('\nOn every re run the random integer remains the same this is another wayout similar to seed method :- '+ str(gen.randint(100,500)))

# Explain a scenario that you must use RandomState before the random generator function.
# 
#  Ans :- Think about a situation where you have 1 matrix which you want to generate into 100 matrixes. So the purpose is that now 
# you have 100 similar data matrices which a professor can distribute in class for diff machine learning problems. And
# also can revert mack to the original matrix by subtracting the random matrix that was added to it.



# 5x5 matrix cent 
# Explain why there are negative values in cent.
# Ans :- This is because the randn genration is based on gausian distribution and the mean is 0 for all the values. 
#       So by this understanding there must be negative values as well.
np.random.seed(5)
cent = np.matrix([[np.random.randn() for e in range(5)] for e in range(5)])
print('\n5*5 matrix cent with random numbers in it on the bases of normal distribution with seed 5 :- \n' + str(cent))

np.random.seed(10)
cent = np.matrix([[np.random.randn() for e in range(5)] for e in range(5)])
print('\n5*5 matrix cent with random numbers in it on the bases of normal distribution with seed 10 :- \n' + str(cent))

# 5x5 matrix cent_fix
generator = np.random.RandomState(5)
cent_fix = np.matrix([[generator.randn() for e in range(5)] for e in range(5)])
print('\n 5*5 matrix cent_fix with random numbers in it using RandomState on the bases of normal distribution :- \n' + str(cent_fix))

generator = np.random.RandomState(6)
cent_fix = np.matrix([[generator.randn() for e in range(5)] for e in range(5)])
print('\n 5*5 matrix cent_fix with random numbers in it using RandomState on the bases of normal distribution :- \n' + str(cent_fix))

# Section 1.11

In [ ]:
'''
Generates a row vector of 5 random numbers drawn from the uniform distribution using rand() 
and assign the vector to a variable v. Then draw another 5 random numbers and concatenate them 
as additional column values to v, and display the new v.
'''

In [ ]:
import numpy as np

v = np.asarray([np.random.rand() for i in range(5)], dtype = float )
v2 = v = np.asarray([np.random.rand() for i in range(5)], dtype = float )

v = np.concatenate((v, v2))

print('Concatenated vector is as follows :- \n'+ str(v))

In [1]:
import matplotlib.pyplot as plt

In [ ]:
plt.