# Question 1 

## Section 1.1 

Import the iris dataset (load_iris) from sklearn datasets and place them in a variable iris 
(iris is a dot-accessible dictionary or a bunch object).

Similar to the example in the course manuscript (section 2.4), apply a Linear SVM on the iris data and name 
the model svc_iris. Then build two models for sepal and petal features and name them as svc_sepal and svc_petal
respectively.

Finally, use these three models for predicting the labels for the classes and save them in
predicted_iris, predicted_sepal, and predicted_petal arrays. 

What is the role of the fit and predict methods?


In [59]:
import numpy as np 
import sklearn as sk
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC

iris = datasets.load_iris(return_X_y=False)
#print(iris)


# Model 1
svc_iris = LinearSVC()
X = iris['data']
Y = iris['target']
model1 = svc_iris.fit(X,Y)
predicted_iris = model1.predict(X)


# Model 2 sepal
svc_sepal = LinearSVC()
X_Sepal = iris['data'][:,[0,1]]
model2 = svc_sepal.fit(X_Sepal, Y)
predicted_sepal = model2.predict(X_Sepal)


# Model 3 petal
svc_petal = LinearSVC()
X_Petal = iris['data'][:,[2,3]]
model3 = svc_petal.fit(X_Petal, Y)
predicted_petal = model3.predict(X_Petal)


print('Prediction for the model 1 svc_iris :- \n'+ str(predicted_iris) )
print('Prediction for the model 2 svc_sepal :- \n'+ str(predicted_sepal) )
print('Prediction for the model 3 svc_petal :- \n'+ str(predicted_petal) )

Prediction for the model 1 svc_iris :- 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Prediction for the model 2 svc_sepal :- 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 2 2 2 1 2 1 2 1 2 1 1 2 1 2 1 2 1 1 1 1 2 1 1 1
 2 2 2 2 2 1 1 1 1 1 0 0 2 1 1 1 1 2 1 1 1 1 1 2 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 1 2 2 2 2 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 1 2
 2 2]
Prediction for the model 3 svc_petal :- 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 0 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2 

<b>Role of fit :- The fit method helps to train the model on the based of training data as
                  per the chosen Machine learning algorithm  
               
Role of predict :- The predict method helps to predict the labels on the testing and 
                   train data as well
                   to the model.
</b>     

Ex:-                
svc_sepal = svm.SVC(kernel = 'linear', C = 1.0)
<br>X_Sepal = iris['data'][:,[0,1]]</br>
<br>model2 = svc_sepal.fit(X_Sepal, Y)</br>
<br>predicted_sepal = model2.predict(X_Sepal)</br>           

## Section 1.2


Calculate and show the quantities 
Accuracy,
Precision,
Recall and F1-score as well as the confusion matrix for all three models (hint: you might use score method in the
sklearn.metrics module).

Compare the results and explain why there are differences in the metric values? 
(Hint: You might refer to the question 1.9 of assignment 1 and check with the confusion
matrixes.)


In [70]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print('Accuracy scores for the 3 models are as follows :- ')
print('Model 1 :- '+ str(accuracy_score(Y, predicted_iris)))
print('Model 2 :- '+ str(accuracy_score(Y, predicted_sepal)))
print('Model 3 :- '+str(accuracy_score(Y, predicted_petal)))


print('\nPrecision scores for the 3 models are as follows :- ')
print('Model 1 :- '+ str(precision_score(Y, predicted_iris, average = 'macro')))
print('Model 2 :- '+ str(precision_score(Y, predicted_sepal, average = 'macro')))
print('Model 3 :- '+ str(precision_score(Y, predicted_petal, average = 'macro')))


print('\nRecall scores for the 3 models are as follows :- ')
print('Model 1 :- '+ str(recall_score(Y, predicted_iris, average = 'macro')))
print('Model 2 :- '+ str(recall_score(Y, predicted_sepal, average = 'macro')))
print('Model 3 :- '+ str(recall_score(Y, predicted_petal, average = 'macro')))


print('\nF1 scores for the 3 models are as follows :- ')
print('Model 1 :- '+ str(f1_score(Y, predicted_iris, average = 'macro')))
print('Model 2 :- '+ str(f1_score(Y, predicted_sepal, average = 'macro')))
print('Model 3 :- '+ str(f1_score(Y, predicted_petal, average = 'macro')))


print('\nConfusion matrix scores for the 3 models are as follows :- ')
print('Model 1 :-\n '+ str(confusion_matrix(Y, predicted_iris, labels=None, sample_weight=None)))
print('Model 2 :-\n '+ str(confusion_matrix(Y, predicted_sepal, labels=None, sample_weight=None)))
print('Model 3 :-\n '+ str(confusion_matrix(Y, predicted_petal, labels=None, sample_weight=None)))

Accuracy scores for the 3 models are as follows :- 
Model 1 :- 0.966666666667
Model 2 :- 0.8
Model 3 :- 0.94

Precision scores for the 3 models are as follows :- 
Model 1 :- 0.966786714686
Model 2 :- 0.801899855988
Model 3 :- 0.939586501267

Recall scores for the 3 models are as follows :- 
Model 1 :- 0.966666666667
Model 2 :- 0.8
Model 3 :- 0.94

F1 scores for the 3 models are as follows :- 
Model 1 :- 0.966663333
Model 2 :- 0.79641909145
Model 3 :- 0.939729972997

Confusion matrix scores for the 3 models are as follows :- 
Model 1 :-
 [[50  0  0]
 [ 0 47  3]
 [ 0  2 48]]
Model 2 :-
 [[49  1  0]
 [ 2 30 18]
 [ 0  9 41]]
Model 3 :-
 [[50  0  0]
 [ 1 45  4]
 [ 0  4 46]]


KeyboardInterrupt: 

<b> Comparing the metric results for the 3 models graphically. Kindly run the code below for the graphical comparison </b>

In [ ]:
models = ('Accuracy', 'Precision', 'Recall', 'F1_score')


model1 = np.array((accuracy_score(Y, predicted_iris),
                   precision_score(Y, predicted_iris, average = 'macro'),
                   recall_score(Y, predicted_iris, average = 'macro'),
                   f1_score(Y, predicted_iris, average = 'macro'))  ,dtype = float)
model2 = np.array((accuracy_score(Y, predicted_sepal),
                   precision_score(Y, predicted_sepal, average = 'macro'),
                   recall_score(Y, predicted_sepal, average = 'macro'),
                   f1_score(Y, predicted_sepal, average = 'macro'))  ,dtype = float)
model3 = np.array((accuracy_score(Y, predicted_petal),
                   precision_score(Y, predicted_petal, average = 'macro'),
                   recall_score(Y, predicted_petal, average = 'macro'),
                   f1_score(Y, predicted_petal, average = 'macro'))  ,dtype = float)                  


locx = np.arange(4)  # the x locations for the groups
width = 0.15       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(locx, model1, width, color='r' )
rects2 = ax.bar(locx + width, model2, width, color='y')
rects3 = ax.bar(locx + width +width , model3, width, color='g')
ax.set_ylabel(' Mean and Standard deviation values')
ax.set_title('Accuracy using Cross validation')
ax.set_xticks(locx + width / 2)
ax.set_xticklabels(models)
ax.set_yticks(np.arange(0, 1.04, 0.05))
        
ax.legend((rects1[0], rects2[0], rects3[0]), ('Model1', 'Model2', 'Model3'))

plt.show()

## Section 1.3 

'''
Estimate the accuracy of a linear SVM on the iris dataset (all data, sepal, and petal) using 10-
fold cross validation and show the mean and standard deviation of the accuracy 
(hint: sklearn provided you the model_selection.cross_val_score function).

Explain briefly what k-fold cross
validation is and what it is used for.

Repeat the experiment with 5-fold cross validation and compare the
results.
'''

In [47]:
from sklearn.model_selection import cross_val_score
import numpy as np
import matplotlib.pyplot as plt

arrCV10 = np.array((cross_val_score(svc_iris, X, Y, cv =10),
                    cross_val_score(svc_iris, X_Sepal, Y, cv =10),
                    cross_val_score(svc_iris, X_Petal, Y, cv =10)), dtype = float)
arrMean10 = [np.mean(arrCV10[i]) for i in range(3)] 
arrStd10 = [np.std(arrCV10[i]) for i in range(3)]

#Explain briefly what k-fold cross validation is and what it is used for.

arrCV5 = np.array((cross_val_score(svc_iris, X, Y, cv =5),
                    cross_val_score(svc_iris, X_Sepal, Y, cv =5),
                    cross_val_score(svc_iris, X_Petal, Y, cv =5)), dtype = float)
arrMean5 = [np.mean(arrCV5[i]) for i in range(3)] 
arrStd5 = [np.std(arrCV5[i]) for i in range(3)]

<b>10 fold crossvalidation results</b>

In [50]:
feature_names = ('Iris model', 'Sepal model', 'Petal model')

N = 3

locx = np.arange(N)  # the x locations for the groups
width = 0.15       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(locx, arrMean10, width, color='r' )
rects2 = ax.bar(locx + width, arrStd10, width, color='y')

ax.set_ylabel(' Mean and Standard deviation values')
ax.set_title('Accuracy using Cross validation')
ax.set_xticks(locx + width / 2)
ax.set_xticklabels(tuple(feature_names))
ax.set_yticks(np.arange(0, 1.04, 0.05))
        
ax.legend((rects1[0], rects2[0]), ('Mean', 'Standard Deviation'))

plt.show()

KeyboardInterrupt: 

<b>5 fold crossvalidation results</b>

In [51]:
feature_names = ('Iris model', 'Sepal model', 'Petal model')

N = 3

locx = np.arange(N)  # the x locations for the groups
width = 0.15       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(locx, arrMean5, width, color='r' )
rects2 = ax.bar(locx + width, arrStd5, width, color='y')

ax.set_ylabel(' Mean and Standard deviation values')
ax.set_title('Accuracy using Cross validation')
ax.set_xticks(locx + width / 2)
ax.set_xticklabels(tuple(feature_names))
ax.set_yticks(np.arange(0, 1.04, 0.05))
        
ax.legend((rects1[0], rects2[0]), ('Mean', 'Standard Deviation'))

plt.show()

KeyboardInterrupt: 

## Section 1.4

Without using sklearn methods related to cross validation,
write a function to implement cross validation and compare the results.

In [52]:
import itertools
import numpy as np

def customizedCrossValidation(model,data,target,cv, ratio):
    CCV = np.ndarray(shape= (1,cv), dtype=float)
    numRows = int(len(target))
    data = np.hstack((data,target.reshape(150,1)))
    for i in range(cv):
        # shuffle
        np.random.shuffle(data)
        limit = int(ratio*len(target))
        # train test split  
        X_train = data[0:limit,[0,1,2,3]]
        Y_train = data[0:limit,[4]]
        X_test = data[limit:numRows,[0,1,2,3]]
        Y_test = data[limit:numRows,[4]]
        # train model 
        trainModel = model.fit(X_train, Y_train)
        y_predicted = trainModel.predict(X_test)
        count = len(y_predicted)
        success = 0
        for j in range(count):
            if(Y_test[j] == y_predicted[j]):
                success +=1
        CCV[0][i] = success/count        
    return CCV    
custResults = customizedCrossValidation(svm.SVC(kernel = 'linear', C= 1.0),X, Y, 10, 0.7)
        
sklearnResults = cross_val_score(svc_iris, X, Y, cv =10)

/home/vishnu/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


<b> Comparing customized and sklearn's crossvalidation results.  Kindly run the below code for the graphical comparison done
 </b>

In [58]:
feature_names = ('customizedCV', 'sklearnCV')

N = 3

arrMean = np.array((np.mean(custResults),np.mean(sklearnResults)), dtype = float)
arrStd = np.array((np.std(custResults),np.std(sklearnResults)), dtype = float)


locx = np.arange(2)  # the x locations for the groups
width = 0.15       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(locx, arrMean, width, color='r' )
rects2 = ax.bar(locx + width, arrStd, width, color='y')

ax.set_ylabel(' Mean and Standard deviation values')
ax.set_title('Accuracy using Cross validation')
ax.set_xticks(locx + width / 2)
ax.set_xticklabels(tuple(feature_names))
ax.set_yticks(np.arange(0, 1.04, 0.05))
        
ax.legend((rects1[0], rects2[0]), ('Mean', 'Standard Deviation'))

plt.show()

KeyboardInterrupt: 